### ISSUE TITLE
GoodbyeDPI не работает

### ISSUE THREAD

**Issue by clirixx** [clirixx/GoodbyeDPI-#1]
Всех приветствую, перестала в службах появляться GoodbyeDPI (Сразу скажу то что файл service_install_russia_blacklist.cmd я запускал и делал ВСЕ ПО ИНСТРУКЦИИ!). Из-за этого перестал работать ютуб и саундклауд. Хотелось бы узнать вашего ответа на мой вопрос как это пофиксить, всем спасибо

**Comment by o4ko228** [comment]
откуда ты ?

**Comment by clirixx** [comment]
с дальнего востока

**Comment by clirixx** [comment]
с дальнего востока

**Comment by clirixx** [comment]
я пофиксил всем спасиб за помощь
